#!/bin/bash

# =================================================================
# Script 5: The Open Source Manifesto Generator
# Author: Atharva Nikam (24BSA10198)
# Course: Open Source Software
# Description: An interactive script that captures personal 
# philosophy and generates a unique Manifesto text file.
# =================================================================

# Requirement: Alias concept demonstration via a comment
# alias show_manifesto='cat manifesto_$(whoami).txt'

echo "------------------------------------------------------------"
echo "  WELCOME TO THE OPEN SOURCE MANIFESTO GENERATOR            "
echo "  Student: Atharva Nikam | Reg: 24BSA10198                 "
echo "------------------------------------------------------------"
echo "Please answer the following three questions to build your statement."
echo ""

# Requirement: Use 'read' for user input with custom prompts
read -p "1. Name one open-source tool you rely on daily: " USER_TOOL
read -p "2. In a single word, what does 'freedom' mean in software? " USER_FREEDOM
read -p "3. What is one thing you'd build and share with the world? " USER_BUILD

# Formatting variables for the final document
CURRENT_DATE=$(date '+%d %B %Y')
OS_USER=$(whoami)
OUTPUT_FILE="manifesto_${OS_USER}.txt"

echo "------------------------------------------------------------"
echo "Processing your inputs and generating the file..."

# Requirement: Compose a paragraph using string concatenation and write to file
# We use '>' to create/overwrite and '>>' to append as per the rubric
echo "PERSONAL OPEN SOURCE MANIFESTO" > "$OUTPUT_FILE"
echo "Generated by: $OS_USER on $CURRENT_DATE" >> "$OUTPUT_FILE"
echo "------------------------------------------------------------" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# The core philosophy paragraph
MANIFESTO_TEXT="As a developer, I recognize that the tools I use, like $USER_TOOL, are built on a foundation of collective intelligence. To me, the essence of open source is $USER_FREEDOM. By standing on the shoulders of giants, I commit to the spirit of transparency. In the future, I aim to contribute by building $USER_BUILD and sharing it freely to empower the global community."

echo "$MANIFESTO_TEXT" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "Signed, Atharva Nikam (24BSA10198)" >> "$OUTPUT_FILE"

# Final confirmation to the user
echo "Success! Your manifesto has been saved to: $OUTPUT_FILE"
echo "------------------------------------------------------------"
echo "PREVIEW OF YOUR MANIFESTO:"
echo ""
cat "$OUTPUT_FILE"
echo ""
echo "------------------------------------------------------------"
